### ISSUE TITLE
Problems with "application" of the code

### ISSUE THREAD

**Issue by aostruszka** [leonardvandriel/caffe2_cpp_tutorial#12]
Dear Leonard

First of all thank you for creating & sharing this tutorial and please accept my apologies for contacting you via "issues" (as this is not really issue with your tutorial, but with an attempt to apply it - and code from [here](https://github.com/bwasti/AICamera/blob/master/app/src/main/cpp/native-lib.cpp#L132) - on my "hello mnist").  I'm not really interested in creating nets in C++ but in loading and using.

As I've said I've tried to come up with simple C++ app ([here](https://github.com/aostruszka/qt-mnist/commits/master)) that should be loading net and using it for predictions but it fails to replicate results that I'm getting on python side. 

If I run `mnist.py` I'll get two ".pb" files with net definition and initialization.  If I load this net on python side and feed it with some image from DB then I'll get correct predictions:
```
timg = np.fromfile('test_img.dat', dtype=np.uint8).reshape([28,28])
workspace.FeedBlob('data', (timg/256.).reshape([1,1,28,28]).astype(np.float32))
workspace.RunNet(net_def.name)
workspace.FetchBlob('softmax')
array([[  1.23242417e-05,   6.76146897e-07,   9.01260137e-06,
          1.60285403e-04,   9.54966026e-07,   6.82772861e-06,
          2.20508967e-09,   9.99059498e-01,   2.71651220e-06,
          7.47664250e-04]], dtype=float32)
```
So it is pretty sure it is '7' but If I load the same net in C++ and run it on the same file then I get completely different results.  My C++ net initialization side looks like:
```
    QByteArray img_bytes;
    caffe2::NetDef init_net, predict_net;
    caffe2::TensorCPU input;
    // predictor and it's input/output vectors
    std::unique_ptr<caffe2::Predictor> predictor;
    caffe2::Predictor::TensorVector input_vec;
    caffe2::Predictor::TensorVector output_vec;
...
    QFile f("mnist_init_net.pb");
...
    auto barr = f.readAll();
    if (! init_net.ParseFromArray(barr.data(), barr.size())) {
...
    f.setFileName("mnist_predict_net.pb");
...
    barr = f.readAll();
    if (! predict_net.ParseFromArray(barr.data(), barr.size())) {
...
    predictor.reset(new caffe2::Predictor(init_net, predict_net));
    input.Resize(std::vector<int>{{1, 1, IMG_H, IMG_W}});
    input_vec.resize(1, &input);
```
and running net is (`img_bytes` is an array keeping img data):
```
    float* data = input.mutable_data<float>();
    for (int i = 0; i < img_bytes.size(); ++i)
        *data++ = float(img_bytes[i])/256.f;

    if (! predictor->run(input_vec, &output_vec) || output_vec.size() < 1
                                                 || output_vec[0]->size() != 10)
...
```
The result on the same file is that '7' is at 17% (not 99.9%) and the remaining categories are around 5-10%.  Right now I'm stuck and I don't know where the problem is, so I'd like to kindly ask you to guide me a bit - if you don't mind and have some spare time :).

Best regards
Andrzej

PS. BTW everything is run on CPU (no CUDA) and on the very same computer if that matters.

**Comment by leonardvandriel** [comment]
Hi Andrzej,

This is likely an issue that is specific to your code. Usually these problems arise from incorrect image parsing, scaling or color adjustment. Looking at the code I'm not able to give you any specific cause, but here are some handles.

If the classification results look pretty much random, i.e. probabilities are evenly distributed at 10% (1 / #labels), then the image is scrambled. This happens when color channels are incorrectly handled (1 vs 3), or when byte order is incorrect (NHWC vs NCHW), or some order offset problem to any of the batch (N) and size (HW).

If the classification works a bit but not that well, then the image geometry is probably fine, but the color or size values are incorrectly scaled or clipped. In particular incorrect scaling of color values is often a problem. The convolutions in the MNIST model used in the Caffe2 tutorial expect float values between 0 and 1, but the model already contains a scaling step that takes byte values and scales them down by factor 256. I see you also do this in code (`float(img_bytes[i])/256.f`). Have you tried running without the scaling?

In general it's important to have debugging tools, e.g. log tensor value to stdout, that allow you to inspect the internal values to make sure all these conditions are met. Especially when there are multiple problems simultaneously it's important to take a look at the actual values. Take a look at `intro.cc` to see how you can log the contents of a tensor in a workspace. The `caffe2::Predictor` doesn't really allow for this easily, so perhaps it's better to setup a workspace yourself.  Take a look at `imagenet.cc` to see how to do this.

**Comment by aostruszka** [comment]
Dear Leonard

You were spot on with your suspicion about scaling (`float(img_bytes[i])/256.f`).
I have not yet learned how to log tensor values but have decided to recompile caffe2 with debuging info and have run simultaneously python and C++ code and by inspecting "Xdata" in ConvOp I've found negative values in C++ resulting from the fact that by default "char" is a signed type :).

Changing this scaling to: `static_cast<unsigned char>(img_bytes[i])/256.f` fixed the problem :).
Thank you for your time and my apologies that you had to waste it for such stupid mistake.

Best regards
Andrzej

**Comment by leonardvandriel** [comment]
great to hear. for me, mistakes like these are usually half of the work :)
