### ISSUE TITLE
Composable network definitions and exchange emails?

### ISSUE THREAD

**Issue by charlesrwest** [leonardvandriel/caffe2_cpp_tutorial#2]
Hey Leonard,

Thank you for publishing this tutorial code.  I've been pondering the best way to go about constructing caffe2 networks in C++ and have recently completed some work that while not complete, might have some potential.

If you have time, please take a look and tell me if you think this might be the way to go or if you have been going in a different direction:
https://github.com/charlesrwest/Caffe2ComputeModules/blob/master/src/executables/trainSineWave/main.cpp

Thanks,
Charlie West

P.S.
I would be interested in corresponding about this.  My email is crwest@ncsu.edu.  Please drop me a line if you would like to talk.

**Comment by leonardvandriel** [comment]
Hi @charlesrwest, thanks sharing your code. I'll take a look and get back to you. Here's some of my general thoughts on Caffe2 and C++ support.

Like with Tensorflow, it makes sense for Caffe2 to have a Python front-end; it's easy to set up and experiment with and you have many scientific, data-processing, and visualization libraries at your disposal. The question then for every piece of functionality that you add, is where to add it: Python or C++. It seems that the Caffe2 people decided to do all model building in Python and write only the necessary core training and prediction code in C++.

I guess that leaves a gap for those who don't want to use Python altogether and instead do even the high-level network design in C++, including adding training and test operators, backpropagation, and visualization. I started working with Caffe2 in C++ because I wanted to brush up my C++ knowledge, but that's quite an unusual requirement. At this point I don't see many reasons to not use Python for developing and training.

If more proof of a need for broad C++ support comes up, I'm willing to invest in more solid C++ framework and perhaps reach out to Caffe2 team to adopt that. For now it makes most sense to keep everything as light-weight as possible. That's why this repo mostly contains state-less utility functions to assist in the bare-minimum of network building.
