### ISSUE TITLE
how can I create all gradient operators in a separate network?

### ISSUE THREAD

**Issue by breadbread1984** [leonardvandriel/caffe2_cpp_tutorial#38]
sometimes, I need to use different kind of loss functions at the end of one network structure. Currently, I have to create several networks with differences only in the last operators. Is there a way to create gradient operators in a separated network with your model helper, so that I can execute forward network, loss value calculating network and backward network sequentially to make it possible. Thx

**Comment by leonardvandriel** [comment]
Interesting question. Currently the gradient ops are added to the same model, but it shouldn't be too hard to add the option for splitting the model. I'll take a look.

I do think it's ultimately better to generate separate models that can be run in full, instead of an ensemble of partial models. There's little memory overhead in creating multiple models, or building them on the fly by duplicating and merging base components. In the end this does create a more clear architecture and it allows Caffe2 to perform internal optimizations on the complete model including gradients. Anyway, not a very strong case I'm trying to make here :)

**Comment by leonardvandriel** [comment]
Hi, in commit bc7ba6657 I added option to provide a target net:

    void AddGradientOps(NetUtil& target) const;

Would that work?

**Comment by breadbread1984** [comment]
thx it works
